import "@patternfly/react-core/dist/styles/base.css";
import "@patternfly/react-styles/css/utilities/Spacing/spacing.css";
import "@patternfly/virtual-assistant/dist/css/main.css";
import type { Metadata } from "next";
import { PageWrapper } from "../components/page-wrapper";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <PageWrapper>{children}</PageWrapper>
      </body>
    </html>
  );
}
